name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_dotenv: ^6.0.1
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  intl: ^0.20.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ============================================================
# FLUTTER
# ============================================================

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/


# ============================================================
# APP LAUNCHER ICON
# ============================================================

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21